### ISSUE TITLE
Error: Decryption failed

### ISSUE THREAD

**Issue by svenmueller** [jbraeuer/raziel#5]
Hi,

i setup my machine like described in the `README.md`. When i try to edit a file using raziel command  i get the following exception from `gpgme`. Any ideas how to get raziel working?

Thanks!

```
$ ./bin/raziel edit ../credentials.yaml.enc
Error: Decryption failed
    /Users/smueller/.rvm/gems/ruby-1.9.3-p327/gems/gpgme-2.0.5/lib/gpgme/ctx.rb:398:in `decrypt_verify'
    /Users/smueller/.rvm/gems/ruby-1.9.3-p327/gems/gpgme-2.0.5/lib/gpgme/crypto.rb:172:in `block in decrypt'
    /Users/smueller/.rvm/gems/ruby-1.9.3-p327/gems/gpgme-2.0.5/lib/gpgme/ctx.rb:71:in `new'
    /Users/smueller/.rvm/gems/ruby-1.9.3-p327/gems/gpgme-2.0.5/lib/gpgme/crypto.rb:170:in `decrypt'
    /Users/smueller/dev/src/raziel/lib/raziel.rb:23:in `decrypt'
    /Users/smueller/dev/src/raziel/lib/raziel.rb:146:in `decrypt_item'
    /Users/smueller/dev/src/raziel/lib/raziel.rb:121:in `block in decrypt_hash'
    /Users/smueller/dev/src/raziel/lib/raziel.rb:114:in `each'
    /Users/smueller/dev/src/raziel/lib/raziel.rb:114:in `decrypt_hash'
    /Users/smueller/dev/src/raziel/lib/raziel.rb:105:in `decrypt'
    ./bin/raziel:94:in `decrypt'
    ./bin/raziel:162:in `edit'
    ./bin/raziel:205:in `run'
    ./bin/raziel:221:in `<main>'
```

used version:

```
$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin13.1.0]
```

```
$ brew list gpgme
/usr/local/Cellar/gpgme/1.4.3/bin/gpgme-config
/usr/local/Cellar/gpgme/1.4.3/include/gpgme.h
/usr/local/Cellar/gpgme/1.4.3/lib/libgpgme-pthread.11.dylib
/usr/local/Cellar/gpgme/1.4.3/lib/libgpgme.11.dylib
/usr/local/Cellar/gpgme/1.4.3/lib/ (4 other files)
/usr/local/Cellar/gpgme/1.4.3/share/aclocal/gpgme.m4
/usr/local/Cellar/gpgme/1.4.3/share/common-lisp/ (3 files)
```

```
$ gem list gpgme aruba cucumber ptools highline

*** LOCAL GEMS ***

gpgme (2.0.5)

*** LOCAL GEMS ***

aruba (0.5.4)

*** LOCAL GEMS ***

cucumber (1.3.14)

*** LOCAL GEMS ***

ptools (1.2.4)

*** LOCAL GEMS ***

highline (1.6.21)
```

**Comment by svenmueller** [comment]
btw...after going back to gpg (GnuPG) 1.4.16 (from 2.x) and gpgme (2.0.2), the error disappears.
